version: '3.8'

services:
  app:
    build: .
    container_name: nest-backend
    restart: always
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/MemoryBook?schema=public
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: MemoryBook
    ports:
      - '5434:5432'
    volumes:
      - ./dump:/docker-entrypoint-initdb.d/